//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 LightAmbient;
//   float4 LightDiffuse;
//   float3 LightDir;
//   float4 MaterialAmbientColor;
//   float4 MaterialDiffuseColor;
//   float MaxBlurFactor;
//   float fHyperfocalDistance;
//   float4x4 mWorld;
//   float4x4 mWorldView;
//   float4x4 mWorldViewProjection;
//   float4 vFocalPlane;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   mWorldViewProjection c0       4
//   mWorld               c4       3
//   mWorldView           c7       3
//   MaterialAmbientColor c10      1
//   MaterialDiffuseColor c11      1
//   LightDir             c12      1
//   LightAmbient         c13      1
//   LightDiffuse         c14      1
//   vFocalPlane          c15      1
//   fHyperfocalDistance  c16      1
//   MaxBlurFactor        c17      1
//

    vs_2_0
    def c18, 0, 1, 0, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    dp4 oPos.x, v0, c0
    dp4 oPos.y, v0, c1
    dp4 oPos.z, v0, c2
    dp4 oPos.w, v0, c3
    dp3 r0.x, v1, c4
    dp3 r0.y, v1, c5
    dp3 r0.z, v1, c6
    dp3 r0.x, r0, c12
    max r0.x, r0.x, c18.x
    mov r1.xyz, c11
    mul r0.yzw, r1.xxyz, c14.xxyz
    mov r1.xyz, c10
    mul r1.xyz, r1, c13
    mad oD0.xyz, r0.yzww, r0.x, r1
    dp4 r0.x, v0, c7
    dp4 r0.y, v0, c8
    dp4 r0.z, v0, c9
    mov r0.w, c18.y
    dp4 r0.x, r0, c15
    mul r0.x, r0.x, c16.x
    mul r0.x, r0.x, r0.x
    min oD0.w, r0.x, c17.x
    mov oT0.xy, v2

// approximately 23 instruction slots used
