//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 Diffuse;
//   float4x4 g_mProj;
//   float4x4 g_mView;
//   float4x4 g_mWorld;
//   float3 g_vLight;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   g_mWorld     c0       4
//   g_mView      c4       4
//   g_mProj      c8       4
//   g_vLight     c12      1
//   Diffuse      c13      1
//

    vs_2_0
    def c14, 1, 0, 0, 0
    dcl_position v0
    dcl_normal v1
    dcl_texcoord v2
    dp4 r0.w, v0, c3
    dp4 r0.x, v0, c0
    dp4 r0.y, v0, c1
    dp4 r0.z, v0, c2
    dp4 r1.x, r0, c4
    dp4 r1.y, r0, c5
    dp4 r1.z, r0, c6
    dp4 r1.w, r0, c7
    mad r0, r0.xyzx, c14.xxxy, c14.yyyx
    dp4 oPos.x, r1, c8
    dp4 oPos.y, r1, c9
    dp4 oPos.z, r1, c10
    dp4 oPos.w, r1, c11
    dp3 r1.x, v1, c0
    dp3 r1.y, v1, c1
    dp3 r1.z, v1, c2
    dp3 r2.x, r1, c4
    dp3 r2.y, r1, c5
    dp3 r2.z, r1, c6
    nrm r1.xyz, r2
    dp4 r2.x, r0, c4
    dp4 r2.y, r0, c5
    dp4 r2.z, r0, c6
    add r0.xyz, -r2, c12
    nrm r3.xyz, r0
    dp3 r0.x, r1, r3
    mul oD0, r0.x, c13
    dp3 r0.x, -r2, r1
    add r0.x, r0.x, r0.x
    mad r0.xyz, r0.x, r1, r2
    mov oT2.xyz, r1
    mov oT1.xyz, r2
    mov r1, c6
    mul r2.xyz, r1.wyzw, c7.zwyw
    mad r2.xyz, r1.zwyw, c7.wyzw, -r2
    dp3 r2.x, r2, c5.yzww
    mul r3.xyz, r1.zwxw, c7.wxzw
    mad r3.xyz, r1.wxzw, c7.zwxw, -r3
    dp3 r2.y, r3, c5.xzww
    mul r3.xyz, r1.wxyw, c7.ywxw
    mad r3.xyz, r1.ywxw, c7.wxyw, -r3
    dp3 r2.z, r3, c5.xyww
    mul r3.xyz, r1.yzxw, c7.zxyw
    mad r3.xyz, r1.zxyw, c7.yzxw, -r3
    dp3 r2.w, r3, c5
    dp4 r0.w, r2, c4
    mul r1.w, r0.w, r0.w
    rcp r0.w, r0.w
    slt r1.w, -r1.w, r1.w
    mul r2, r1.zyxz, c5.yzzx
    mul r3, r1.zyxz, c7.yzzx
    mul r4.x, r3.y, c5.w
    mad r2.x, r2.x, c7.w, r4.x
    mov r4.xyz, c7
    mul r5, r4.zyxz, c5.yzzx
    mad r2.x, r5.y, c6.w, r2.x
    mad r2.x, r5.x, -c6.w, r2.x
    mad r2.x, r2.y, -c7.w, r2.x
    mad r6.x, r3.x, -c5.w, r2.x
    mul r7, r1.yzzx, c4.zyxz
    mul r1.z, r7.x, c7.w
    mul r8, r4.yzzx, c4.zyxz
    mad r1.z, r8.y, c6.w, r1.z
    mad r1.z, r3.x, c4.w, r1.z
    mad r1.z, r7.y, -c7.w, r1.z
    mad r1.z, r3.y, -c4.w, r1.z
    mad r6.y, r8.x, -c6.w, r1.z
    mul r1.z, r5.x, c4.w
    mov r9.xyz, c5
    mul r10, r9.zyxz, c4.yzzx
    mad r1.z, r10.x, c7.w, r1.z
    mad r1.z, r8.x, c5.w, r1.z
    mad r1.z, r8.y, -c5.w, r1.z
    mad r1.z, r10.y, -c7.w, r1.z
    mad r6.z, r5.y, -c4.w, r1.z
    mul r6.xyz, r0.w, r6
    mul r6.xyz, r1.w, r6
    dp3 oT3.x, r0, r6
    mul r1.z, r2.z, c7.w
    mad r1.z, r5.w, c6.w, r1.z
    mad r1.z, r3.w, c5.w, r1.z
    mad r1.z, r2.w, -c7.w, r1.z
    mad r1.z, r3.z, -c5.w, r1.z
    mad r2.x, r5.z, -c6.w, r1.z
    mul r1.z, r3.z, c4.w
    mad r1.z, r7.z, c7.w, r1.z
    mad r1.z, r8.w, c6.w, r1.z
    mad r1.z, r8.z, -c6.w, r1.z
    mad r1.z, r7.w, -c7.w, r1.z
    mad r2.y, r3.w, -c4.w, r1.z
    mul r1.z, r10.z, c7.w
    mad r1.z, r8.z, c5.w, r1.z
    mad r1.z, r5.z, c4.w, r1.z
    mad r1.z, r10.w, -c7.w, r1.z
    mad r1.z, r5.w, -c4.w, r1.z
    mad r2.z, r8.w, -c5.w, r1.z
    mul r2.xyz, r0.w, r2
    mul r2.xyz, r1.w, r2
    dp3 oT3.y, r0, r2
    mul r2.xy, r1.yxzw, c5
    mul r2.zw, r1.xyyx, c7.xyxy
    mul r1.z, r2.w, c5.w
    mad r1.z, r2.x, c7.w, r1.z
    mul r3.xy, r4.yxzw, c5
    mad r1.z, r3.y, c6.w, r1.z
    mad r1.z, r3.x, -c6.w, r1.z
    mad r1.z, r2.y, -c7.w, r1.z
    mad r5.x, r2.z, -c5.w, r1.z
    mul r1.xy, r1, c4.yxzw
    mul r1.x, r1.x, c7.w
    mul r2.xy, r4, c4.yxzw
    mad r1.x, r2.y, c6.w, r1.x
    mad r1.x, r2.z, c4.w, r1.x
    mad r1.x, r1.y, -c7.w, r1.x
    mad r1.x, r2.w, -c4.w, r1.x
    mad r5.y, r2.x, -c6.w, r1.x
    mul r1.x, r3.x, c4.w
    mul r1.yz, r9.xyxw, c4.xxyw
    mad r1.x, r1.y, c7.w, r1.x
    mad r1.x, r2.x, c5.w, r1.x
    mad r1.x, r2.y, -c5.w, r1.x
    mad r1.x, r1.z, -c7.w, r1.x
    mad r5.z, r3.y, -c4.w, r1.x
    mul r1.xyz, r0.w, r5
    mul r1.xyz, r1, r1.w
    dp3 oT3.z, r0, r1
    mov oT0.xy, v2

// approximately 131 instruction slots used
