//
// FX Version: fx_4_0
// Child effect (requires effect pool): false
//
// 1 local buffer(s)
//
cbuffer $Globals
{
    float4x4 g_mWorldViewProj;          // Offset:    0, size:   64
    float4x4 g_mWorld;                  // Offset:   64, size:   64
    float3  g_vWorldLightDir = { -0.707000017, 0.707000017, 0 };// Offset:  128, size:   12
    float   g_fTime;                    // Offset:  140, size:    4
    float   g_fElapsedTime;             // Offset:  144, size:    4
    float3  g_vEyePt;                   // Offset:  148, size:   12
}

//
// 8 local object(s)
//
Texture2D g_txDiffuse;
Texture2D g_txNormal;
SamplerState DiffuseSampler
{
    Texture  = g_txDiffuse;
    AddressU = uint(WRAP /* 1 */);
    AddressV = uint(WRAP /* 1 */);
};
SamplerState NormalSampler
{
    Texture  = g_txNormal;
    AddressU = uint(WRAP /* 1 */);
    AddressV = uint(WRAP /* 1 */);
};
BlendState NoBlending
{
    AlphaToCoverageEnable = bool(FALSE /* 0 */);
    BlendEnable[0] = bool(FALSE /* 0 */);
};
DepthStencilState EnableDepth
{
    DepthEnable = bool(TRUE /* 1 */);
    DepthWriteMask = uint(ALL /* 1 */);
};
RasterizerState CullBack
{
    FillMode = uint(SOLID /* 3 */);
    CullMode = uint(BACK /* 3 */);
};
RasterizerState Wireframe
{
    FillMode = uint(WIREFRAME /* 2 */);
    CullMode = uint(BACK /* 3 */);
};

//
// 3 technique(s)
//
technique10 RenderTileDiff10
{
    pass p0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4x4 g_mWorldViewProj;         // Offset:    0 Size:    64
            //   float4x4 g_mWorld;                 // Offset:   64 Size:    64
            //   float3 g_vWorldLightDir;           // Offset:  128 Size:    12 [unused]
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float g_fTime;                     // Offset:  140 Size:     4 [unused]
            //   float g_fElapsedTime;              // Offset:  144 Size:     4 [unused]
            //   float3 g_vEyePt;                   // Offset:  148 Size:    12
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // $Globals                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyzw        0     NONE   float   xyzw
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 0   xy          2     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyz         3     NONE   float   xyz 
            //
            vs_4_0
            dcl_constantbuffer CB0[10], immediateIndexed
            dcl_input v0.xyzw
            dcl_input v1.xyz
            dcl_input v2.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xyz
            dcl_output o2.xy
            dcl_output o3.xyz
            dcl_temps 1
            dp4 o0.x, v0.xyzw, cb0[0].xyzw
            dp4 o0.y, v0.xyzw, cb0[1].xyzw
            dp4 o0.z, v0.xyzw, cb0[2].xyzw
            dp4 o0.w, v0.xyzw, cb0[3].xyzw
            dp3 r0.x, v1.xyzx, cb0[4].xyzx
            dp3 r0.y, v1.xyzx, cb0[5].xyzx
            dp3 r0.z, v1.xyzx, cb0[6].xyzx
            dp3 r0.w, r0.xyzx, r0.xyzx
            rsq r0.w, r0.w
            mul o1.xyz, r0.wwww, r0.xyzx
            mov o2.xy, v2.xyxx
            add o3.xyz, -v0.xyzx, cb0[9].yzwy
            ret 
            // Approximately 13 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4x4 g_mWorldViewProj;         // Offset:    0 Size:    64 [unused]
            //   float4x4 g_mWorld;                 // Offset:   64 Size:    64 [unused]
            //   float3 g_vWorldLightDir;           // Offset:  128 Size:    12
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float g_fTime;                     // Offset:  140 Size:     4 [unused]
            //   float g_fElapsedTime;              // Offset:  144 Size:     4 [unused]
            //   float3 g_vEyePt;                   // Offset:  148 Size:    12 [unused]
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // DiffuseSampler                    sampler      NA          NA             s0      1 
            // DiffuseSampler                    texture  float4          2d             t0      1 
            // $Globals                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyz         3     NONE   float       
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer CB0[9], immediateIndexed
            dcl_sampler s0, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_input_ps linear v1.xyz
            dcl_input_ps linear v2.xy
            dcl_output o0.xyzw
            dcl_temps 2
            dp3_sat r0.x, v1.xyzx, cb0[8].xyzx
            max r0.x, r0.x, l(0.300000)
            sample r1.xyzw, v2.xyxx, t0.xyzw, s0
            mul o0.xyzw, r0.xxxx, r1.xyzw
            ret 
            // Approximately 5 instruction slots used
                    
        };
        DS_StencilRef = uint(0);
        DepthStencilState = EnableDepth;
        AB_BlendFactor = float4(0, 0, 0, 0);
        AB_SampleMask = uint(0xffffffff);
        BlendState = NoBlending;
        RasterizerState = CullBack;
    }

}

technique10 RenderTileBump10
{
    pass p0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4x4 g_mWorldViewProj;         // Offset:    0 Size:    64
            //   float4x4 g_mWorld;                 // Offset:   64 Size:    64
            //   float3 g_vWorldLightDir;           // Offset:  128 Size:    12 [unused]
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float g_fTime;                     // Offset:  140 Size:     4 [unused]
            //   float g_fElapsedTime;              // Offset:  144 Size:     4 [unused]
            //   float3 g_vEyePt;                   // Offset:  148 Size:    12
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // $Globals                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyzw        0     NONE   float   xyzw
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 0   xy          2     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyz         3     NONE   float   xyz 
            //
            vs_4_0
            dcl_constantbuffer CB0[10], immediateIndexed
            dcl_input v0.xyzw
            dcl_input v1.xyz
            dcl_input v2.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xyz
            dcl_output o2.xy
            dcl_output o3.xyz
            dcl_temps 1
            dp4 o0.x, v0.xyzw, cb0[0].xyzw
            dp4 o0.y, v0.xyzw, cb0[1].xyzw
            dp4 o0.z, v0.xyzw, cb0[2].xyzw
            dp4 o0.w, v0.xyzw, cb0[3].xyzw
            dp3 r0.x, v1.xyzx, cb0[4].xyzx
            dp3 r0.y, v1.xyzx, cb0[5].xyzx
            dp3 r0.z, v1.xyzx, cb0[6].xyzx
            dp3 r0.w, r0.xyzx, r0.xyzx
            rsq r0.w, r0.w
            mul o1.xyz, r0.wwww, r0.xyzx
            mov o2.xy, v2.xyxx
            add o3.xyz, -v0.xyzx, cb0[9].yzwy
            ret 
            // Approximately 13 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4x4 g_mWorldViewProj;         // Offset:    0 Size:    64 [unused]
            //   float4x4 g_mWorld;                 // Offset:   64 Size:    64 [unused]
            //   float3 g_vWorldLightDir;           // Offset:  128 Size:    12
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float g_fTime;                     // Offset:  140 Size:     4 [unused]
            //   float g_fElapsedTime;              // Offset:  144 Size:     4 [unused]
            //   float3 g_vEyePt;                   // Offset:  148 Size:    12 [unused]
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // DiffuseSampler                    sampler      NA          NA             s0      1 
            // NormalSampler                     sampler      NA          NA             s1      1 
            // DiffuseSampler                    texture  float4          2d             t0      1 
            // NormalSampler                     texture  float4          2d             t1      1 
            // $Globals                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // TEXCOORD                 0   xyz         1     NONE   float       
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyz         3     NONE   float   xyz 
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer CB0[9], immediateIndexed
            dcl_sampler s0, mode_default
            dcl_sampler s1, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_resource_texture2d (float,float,float,float) t1
            dcl_input_ps linear v2.xy
            dcl_input_ps linear v3.xyz
            dcl_output o0.xyzw
            dcl_temps 2
            dp3 r0.x, v3.xyzx, v3.xyzx
            rsq r0.x, r0.x
            mad r0.xyz, v3.xyzx, r0.xxxx, cb0[8].xyzx
            dp3 r0.w, r0.xyzx, r0.xyzx
            rsq r0.w, r0.w
            mul r0.xyz, r0.wwww, r0.xyzx
            sample r1.xyzw, v2.xyxx, t1.xyzw, s1
            mad r1.xyz, r1.xzyx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
            mov r1.w, -r1.z
            dp3_sat r0.x, r0.xyzx, r1.xywx
            dp3_sat r0.y, r1.xywx, cb0[8].xyzx
            max r0.y, r0.y, l(0.300000)
            log r0.x, r0.x
            mul r0.x, r0.x, l(16.000000)
            exp r0.x, r0.x
            sample r1.xyzw, v2.xyxx, t0.xyzw, s0
            mad o0.xyzw, r1.xyzw, r0.yyyy, r0.xxxx
            ret 
            // Approximately 18 instruction slots used
                    
        };
        DS_StencilRef = uint(0);
        DepthStencilState = EnableDepth;
        AB_BlendFactor = float4(0, 0, 0, 0);
        AB_SampleMask = uint(0xffffffff);
        BlendState = NoBlending;
        RasterizerState = CullBack;
    }

}

technique10 RenderTileWire10
{
    pass p0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4x4 g_mWorldViewProj;         // Offset:    0 Size:    64
            //   float4x4 g_mWorld;                 // Offset:   64 Size:    64
            //   float3 g_vWorldLightDir;           // Offset:  128 Size:    12 [unused]
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float g_fTime;                     // Offset:  140 Size:     4 [unused]
            //   float g_fElapsedTime;              // Offset:  144 Size:     4 [unused]
            //   float3 g_vEyePt;                   // Offset:  148 Size:    12
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // $Globals                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyzw        0     NONE   float   xyzw
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 0   xy          2     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyz         3     NONE   float   xyz 
            //
            vs_4_0
            dcl_constantbuffer CB0[10], immediateIndexed
            dcl_input v0.xyzw
            dcl_input v1.xyz
            dcl_input v2.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xyz
            dcl_output o2.xy
            dcl_output o3.xyz
            dcl_temps 1
            dp4 o0.x, v0.xyzw, cb0[0].xyzw
            dp4 o0.y, v0.xyzw, cb0[1].xyzw
            dp4 o0.z, v0.xyzw, cb0[2].xyzw
            dp4 o0.w, v0.xyzw, cb0[3].xyzw
            dp3 r0.x, v1.xyzx, cb0[4].xyzx
            dp3 r0.y, v1.xyzx, cb0[5].xyzx
            dp3 r0.z, v1.xyzx, cb0[6].xyzx
            dp3 r0.w, r0.xyzx, r0.xyzx
            rsq r0.w, r0.w
            mul o1.xyz, r0.wwww, r0.xyzx
            mov o2.xy, v2.xyxx
            add o3.xyz, -v0.xyzx, cb0[9].yzwy
            ret 
            // Approximately 13 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4x4 g_mWorldViewProj;         // Offset:    0 Size:    64 [unused]
            //   float4x4 g_mWorld;                 // Offset:   64 Size:    64 [unused]
            //   float3 g_vWorldLightDir;           // Offset:  128 Size:    12
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float g_fTime;                     // Offset:  140 Size:     4 [unused]
            //   float g_fElapsedTime;              // Offset:  144 Size:     4 [unused]
            //   float3 g_vEyePt;                   // Offset:  148 Size:    12 [unused]
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // DiffuseSampler                    sampler      NA          NA             s0      1 
            // DiffuseSampler                    texture  float4          2d             t0      1 
            // $Globals                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyz         3     NONE   float       
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer CB0[9], immediateIndexed
            dcl_sampler s0, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_input_ps linear v1.xyz
            dcl_input_ps linear v2.xy
            dcl_output o0.xyzw
            dcl_temps 2
            dp3_sat r0.x, v1.xyzx, cb0[8].xyzx
            max r0.x, r0.x, l(0.300000)
            sample r1.xyzw, v2.xyxx, t0.xyzw, s0
            mul o0.xyzw, r0.xxxx, r1.xyzw
            ret 
            // Approximately 5 instruction slots used
                    
        };
        DS_StencilRef = uint(0);
        DepthStencilState = EnableDepth;
        AB_BlendFactor = float4(0, 0, 0, 0);
        AB_SampleMask = uint(0xffffffff);
        BlendState = NoBlending;
        RasterizerState = Wireframe;
    }

}

