//
// FX Version: fx_4_0
// Child effect (requires effect pool): false
//
// 1 local buffer(s)
//
cbuffer $Globals
{
    float4x4 g_mInvWorldViewProjection; // Offset:    0, size:   64
}

//
// 4 local object(s)
//
TextureCube g_EnvironmentTexture;
SamplerState g_samPointCube
{
    Filter   = uint(MIN_MAG_MIP_POINT /* 0 */);
    AddressU = uint(CLAMP /* 3 */);
    AddressV = uint(CLAMP /* 3 */);
};
SamplerState g_samLinearCube
{
    Filter   = uint(MIN_MAG_MIP_LINEAR /* 21 */);
    AddressU = uint(CLAMP /* 3 */);
    AddressV = uint(CLAMP /* 3 */);
};
DepthStencilState DisableDepth
{
    DepthEnable = bool(FALSE /* 0 */);
    DepthWriteMask = uint(ZERO /* 0 */);
};

//
// 1 technique(s)
//
technique10 Skybox
{
    pass p0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4x4 g_mInvWorldViewProjection;// Offset:    0 Size:    64
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // $Globals                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyzw        0     NONE   float   xyzw
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_POSITION              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            //
            vs_4_0
            dcl_constantbuffer CB0[4], immediateIndexed
            dcl_input v0.xyzw
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xyz
            dcl_temps 1
            mov o0.xyzw, v0.xyzw
            dp4 r0.w, v0.xyzw, cb0[3].xyzw
            dp4 r0.x, v0.xyzw, cb0[0].xyzw
            dp4 r0.y, v0.xyzw, cb0[1].xyzw
            dp4 r0.z, v0.xyzw, cb0[2].xyzw
            dp4 r0.w, r0.xyzw, r0.xyzw
            rsq r0.w, r0.w
            mul o1.xyz, r0.wwww, r0.xyzx
            ret 
            // Approximately 9 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // g_samPointCube                    sampler      NA          NA             s0      1 
            // g_EnvironmentTexture              texture  float4        cube             t0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_POSITION              0   xyzw        0      POS   float       
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_sampler s0, mode_default
            dcl_resource_texturecube (float,float,float,float) t0
            dcl_input_ps linear v1.xyz
            dcl_output o0.xyzw
            sample o0.xyzw, v1.xyzx, t0.xyzw, s0
            ret 
            // Approximately 2 instruction slots used
                    
        };
        DS_StencilRef = uint(0);
        DepthStencilState = DisableDepth;
    }

}

