//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float3 LuminanceConv;
//   sampler2D g_samSrcColor;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   LuminanceConv c0       1
//   g_samSrcColor s0       1
//

    ps_2_0
    dcl t0.xy
    dcl_2d s0
    texld r0, t0, s0
    dp3 r0, r0, c0
    mov oC0, r0

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
