//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   sampler2D PointSampler;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   PointSampler s0       1
//

    ps_2_0
    dcl_centroid t0.xy
    dcl_2d s0
    texld r0, t0, s0
    mov oC0, r0

// approximately 2 instruction slots used (1 texture, 1 arithmetic)
