//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Note: shader requires additional functionality:
//       Tiled resources
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// samp0                             sampler      NA          NA             s0      1 
// samp1                           sampler_c      NA          NA             s1      1 
// tex8                              texture  float4        cube             t8      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   x           0     NONE     int   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_sampler s0, mode_default
dcl_sampler s1, mode_comparison
dcl_resource_texturecube (float,float,float,float) t8
dcl_input_ps constant v0.x
dcl_output o0.xyzw
dcl_temps 7
itof r0.xyzw, l(0, 0, 0, 0)
itof r1.xyz, v0.xxxx
itof r1.w, v0.x
mov r2.x, v0.x
itof r2.y, v0.x
itof r2.z, v0.x
itof r3.xyz, v0.xxxx
itof r4.xyz, v0.xxxx
itof r2.w, v0.x
gather4_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0.x
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s0.x
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0.x
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s0.x
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0.y
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s0.y
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0.z
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s0.z
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0.w
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s0.w
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s1.x, r1.w
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s1.x, r1.w
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s1.x, r1.w
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s1.x, r1.w
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s1.y, r1.w
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s1.y, r1.w
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s1.z, r1.w
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s1.z, r1.w
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s1.w, r1.w
add r0.xyzw, r0.xyzw, r5.xyzw
gather4_c_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r6.x, r1.xyzx, t8.xyzw, s1.w, r1.w
check_access_fully_mapped r3.w, r6.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r3.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
resinfo_indexable(texturecube)(float,float,float,float)_uint r5.xyz, r2.x, t8.xywz
mov r5.x, r5.x
mov r5.y, r5.y
mov r5.z, r5.z
utof r6.xyzw, r5.xxxx
add r0.xyzw, r0.xyzw, r6.xyzw
utof r6.xyzw, r5.yyyy
add r0.xyzw, r0.xyzw, r6.xyzw
utof r5.xyzw, r5.zzzz
add r0.xyzw, r0.xyzw, r5.xyzw
sample_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0
add r0.xyzw, r0.xyzw, r5.xyzw
sample_cl_s_indexable(texturecube)(float,float,float,float) r5.xyzw, null, r1.xyzx, t8.xyzw, s0, r2.y
add r0.xyzw, r0.xyzw, r5.xyzw
sample_cl_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r2.x, r1.xyzx, t8.xyzw, s0, r2.y
check_access_fully_mapped r2.x, r2.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r2.xxxx, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
sample_b_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0, r2.z
add r0.xyzw, r0.xyzw, r5.xyzw
sample_b_cl_s_indexable(texturecube)(float,float,float,float) r5.xyzw, null, r1.xyzx, t8.xyzw, s0, r2.z, r2.y
add r0.xyzw, r0.xyzw, r5.xyzw
sample_b_cl_s_indexable(texturecube)(float,float,float,float) r5.xyzw, r2.x, r1.xyzx, t8.xyzw, s0, r2.z, r2.y
check_access_fully_mapped r2.x, r2.x
add r0.xyzw, r0.xyzw, r5.xyzw
and r5.xyzw, r2.xxxx, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
sample_c_indexable(texturecube)(float,float,float,float) r2.x, r1.xyzx, t8.xxxx, s1, r1.w
add r0.xyzw, r0.xyzw, r2.xxxx
sample_c_cl_s_indexable(texturecube)(float,float,float,float) r2.x, null, r1.xyzx, t8.xxxx, s1, r1.w, r2.y
add r0.xyzw, r0.xyzw, r2.xxxx
sample_c_cl_s_indexable(texturecube)(float,float,float,float) r2.x, r5.x, r1.xyzx, t8.xxxx, s1, r1.w, r2.y
check_access_fully_mapped r2.z, r5.x
add r0.xyzw, r0.xyzw, r2.xxxx
and r5.xyzw, r2.zzzz, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
sample_c_lz_indexable(texturecube)(float,float,float,float) r2.x, r1.xyzx, t8.xxxx, s1, r1.w
add r0.xyzw, r0.xyzw, r2.xxxx
sample_c_lz_indexable(texturecube)(float,float,float,float) r2.x, r1.xyzx, t8.xxxx, s1, r1.w
add r0.xyzw, r0.xyzw, r2.xxxx
sample_c_lz_s_indexable(texturecube)(float,float,float,float) r2.x, r5.x, r1.xyzx, t8.xxxx, s1, r1.w
check_access_fully_mapped r1.w, r5.x
add r0.xyzw, r0.xyzw, r2.xxxx
and r5.xyzw, r1.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r5.xyzw
sample_d_indexable(texturecube)(float,float,float,float) r5.xyzw, r1.xyzx, t8.xyzw, s0, r3.xyzx, r4.xyzx
add r0.xyzw, r0.xyzw, r5.xyzw
sample_d_cl_s_indexable(texturecube)(float,float,float,float) r5.xyzw, null, r1.xyzx, t8.xyzw, s0, r3.xyzx, r4.xyzx, r2.y
add r0.xyzw, r0.xyzw, r5.xyzw
sample_d_cl_s_indexable(texturecube)(float,float,float,float) r3.xyzw, r2.x, r1.xyzx, t8.xyzw, s0, r3.xyzx, r4.xyzx, r2.y
check_access_fully_mapped r1.w, r2.x
add r0.xyzw, r0.xyzw, r3.xyzw
and r3.xyzw, r1.wwww, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r3.xyzw
sample_l_indexable(texturecube)(float,float,float,float) r3.xyzw, r1.xyzx, t8.xyzw, s0, r2.w
add r0.xyzw, r0.xyzw, r3.xyzw
sample_l_s_indexable(texturecube)(float,float,float,float) r1.xyzw, r2.x, r1.xyzx, t8.xyzw, s0, r2.w
check_access_fully_mapped r2.x, r2.x
add r0.xyzw, r0.xyzw, r1.xyzw
and r1.xyzw, r2.xxxx, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
add r0.xyzw, r0.xyzw, r1.xyzw
mov o0.xyzw, r0.xyzw
ret 
// Approximately 143 instruction slots used
