//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   bool $RGB16;
//   bool $RGBE8;
//   samplerCUBE CubeSampler;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   $RGBE8       c0       1
//   $RGB16       c1       1
//   CubeSampler  s3       1
//

    ps_2_0
    def c2, 255, -128, 100, 0.200000003
    def c3, 0, 0, 0.400000006, 0.00392156886
    def c4, 1, 0, 0.00999999978, 0
    dcl t0.xyz
    dcl t1.xyz
    dcl_cube s3
    mov r0.xyz, t0
    dp3 r0.w, t1, r0
    add r0.w, r0.w, r0.w
    mad r0.xyz, r0, -r0.w, t1
    texld r0, r0, s3
    mad r0.w, r0.w, c2.x, c2.y
    exp r0.w, r0.w
    mul r1.xyz, r0.w, r0
    mul r2.xyz, r0, c2.z
    cmp r0.xyz, -c1.x, r0, r2
    cmp r0.xyz, -c0.x, r0, r1
    mul_sat r1.xyz, t0.y, c3
    add r2.xy, r0, -r1.y
    add r2.z, r0.z, -r1.z
    mad r0.xyz, r2, c2.w, r1
    max r1.x, r0.x, r0.y
    max r2.x, r1.x, r0.z
    log r0.w, r2.x
    frc r1.x, -r0.w
    add r0.w, r0.w, r1.x
    exp r1.x, r0.w
    add r0.w, r0.w, -c2.y
    mul r2.w, r0.w, c3.w
    rcp r0.w, r1.x
    mul r2.xyz, r0.w, r0
    mul r1.xyz, r0, c4.z
    cmp r0.xyz, -c1.x, r0, r1
    mov r1.x, c1.x
    cmp r0.w, -r1.x, c4.x, c4.y
    cmp r0, -c0.x, r0, r2
    mov oC0, r0

// approximately 31 instruction slots used (1 texture, 30 arithmetic)
