//
// FX Version: fx_4_0
// Child effect (requires effect pool): false
//
// 2 local buffer(s)
//
cbuffer cb0
{
    float3  g_vLightDir = { -0.707000017, 0.707000017, 0 };// Offset:    0, size:   12
    float4  g_vColor = { 1, 1, 0.800000012, 1 };// Offset:   16, size:   16
}

cbuffer cb1
{
    float4x4 g_mWorld;                  // Offset:    0, size:   64
    float4x4 g_mWorldViewProjection;    // Offset:   64, size:   64
}

//
// 1 local object(s)
//
BlendState NoBlending
{
    AlphaToCoverageEnable = bool(FALSE /* 0 */);
    BlendEnable[0] = bool(FALSE /* 0 */);
};

//
// 1 technique(s)
//
technique10 Render
{
    pass P0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer cb1
            // {
            //
            //   float4x4 g_mWorld;                 // Offset:    0 Size:    64
            //   float4x4 g_mWorldViewProjection;   // Offset:   64 Size:    64
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // cb1                               cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyz         0     NONE   float   xyz 
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            //
            vs_4_0
            dcl_constantbuffer CB0[8], immediateIndexed
            dcl_input v0.xyz
            dcl_input v1.xyz
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xyz
            dcl_temps 1
            mov r0.xyz, v0.xyzx
            mov r0.w, l(1.000000)
            dp4 o0.x, r0.xyzw, cb0[4].xyzw
            dp4 o0.y, r0.xyzw, cb0[5].xyzw
            dp4 o0.z, r0.xyzw, cb0[6].xyzw
            dp4 o0.w, r0.xyzw, cb0[7].xyzw
            dp3 o1.x, v1.xyzx, cb0[0].xyzx
            dp3 o1.y, v1.xyzx, cb0[1].xyzx
            dp3 o1.z, v1.xyzx, cb0[2].xyzx
            ret 
            // Approximately 10 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer cb0
            // {
            //
            //   float3 g_vLightDir;                // Offset:    0 Size:    12
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float4 g_vColor;                   // Offset:   16 Size:    16
            //      = 0x3f800000 0x3f800000 0x3f4ccccd 0x3f800000 
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // cb0                               cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer CB0[2], immediateIndexed
            dcl_input_ps linear v1.xyz
            dcl_output o0.xyzw
            dcl_temps 1
            dp3 r0.x, v1.xyzx, v1.xyzx
            rsq r0.x, r0.x
            mul r0.xyz, r0.xxxx, v1.xyzx
            dp3_sat r0.x, r0.xyzx, cb0[0].xyzx
            mul o0.xyzw, r0.xxxx, cb0[1].xyzw
            ret 
            // Approximately 6 instruction slots used
                    
        };
        AB_BlendFactor = float4(0, 0, 0, 0);
        AB_SampleMask = uint(0xffffffff);
        BlendState = NoBlending;
    }

}

