//
// FX Version: fx_5_0
//
// 3 local buffer(s)
//
cbuffer cbConstant
{
    float3  vLightDir = { -0.577000022, 0.577000022, -0.577000022 };// Offset:    0, size:   12
}

cbuffer cbChangesEveryFrame
{
    float4x4 World;                     // Offset:    0, size:   64
    float4x4 View;                      // Offset:   64, size:   64
    float4x4 Projection;                // Offset:  128, size:   64
    float   Time;                       // Offset:  192, size:    4
}

cbuffer cbUserChanges
{
    float   Waviness;                   // Offset:    0, size:    4
}

//
// 4 local object(s)
//
Texture2D g_txDiffuse;
SamplerState samLinear
{
    Filter   = uint(MIN_MAG_MIP_LINEAR /* 21 */);
    AddressU = uint(WRAP /* 1 */);
    AddressV = uint(WRAP /* 1 */);
};
DepthStencilState EnableDepth
{
    DepthEnable = bool(TRUE /* 1 */);
    DepthWriteMask = uint(ALL /* 1 */);
    DepthFunc = uint(LESS_EQUAL /* 4 */);
};
BlendState NoBlending
{
    AlphaToCoverageEnable = bool(FALSE /* 0 */);
    BlendEnable[0] = bool(FALSE /* 0 */);
};

//
// 1 groups(s)
//
fxgroup
{
    //
    // 1 technique(s)
    //
    technique11 Render
    {
        pass P0
        {
            VertexShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 10.1
                //
                //
                // Buffer Definitions: 
                //
                // cbuffer cbChangesEveryFrame
                // {
                //
                //   float4x4 World;                    // Offset:    0 Size:    64
                //   float4x4 View;                     // Offset:   64 Size:    64
                //   float4x4 Projection;               // Offset:  128 Size:    64
                //   float Time;                        // Offset:  192 Size:     4
                //
                // }
                //
                // cbuffer cbUserChanges
                // {
                //
                //   float Waviness;                    // Offset:    0 Size:     4
                //
                // }
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim      HLSL Bind  Count
                // ------------------------------ ---------- ------- ----------- -------------- ------
                // cbChangesEveryFrame               cbuffer      NA          NA            cb0      1 
                // cbUserChanges                     cbuffer      NA          NA            cb1      1 
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // POSITION                 0   xyz         0     NONE   float   xyz 
                // NORMAL                   0   xyz         1     NONE   float   xyz 
                // TEXCOORD                 0   xy          2     NONE   float   xy  
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_POSITION              0   xyzw        0      POS   float   xyzw
                // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                // TEXCOORD                 1   xy          2     NONE   float   xy  
                //
                vs_4_0
                dcl_constantbuffer CB0[13], immediateIndexed
                dcl_constantbuffer CB1[1], immediateIndexed
                dcl_input v0.xyz
                dcl_input v1.xyz
                dcl_input v2.xy
                dcl_output_siv o0.xyzw, position
                dcl_output o1.xyz
                dcl_output o2.xy
                dcl_temps 3
                mov r0.xyz, v0.xyzx
                mov r0.w, l(1.000000)
                dp4 r1.x, r0.xyzw, cb0[0].xyzw
                dp4 r2.y, r0.xyzw, cb0[1].xyzw
                mad r1.y, r2.y, l(0.100000), cb0[12].x
                sincos r1.y, null, r1.y
                mad r2.x, r1.y, cb1[0].x, r1.x
                dp4 r2.z, r0.xyzw, cb0[2].xyzw
                dp4 r2.w, r0.xyzw, cb0[3].xyzw
                dp4 r0.x, r2.xyzw, cb0[4].xyzw
                dp4 r0.y, r2.xyzw, cb0[5].xyzw
                dp4 r0.z, r2.xyzw, cb0[6].xyzw
                dp4 r0.w, r2.xyzw, cb0[7].xyzw
                dp4 o0.x, r0.xyzw, cb0[8].xyzw
                dp4 o0.y, r0.xyzw, cb0[9].xyzw
                dp4 o0.z, r0.xyzw, cb0[10].xyzw
                dp4 o0.w, r0.xyzw, cb0[11].xyzw
                dp3 o1.x, v1.xyzx, cb0[0].xyzx
                dp3 o1.y, v1.xyzx, cb0[1].xyzx
                dp3 o1.z, v1.xyzx, cb0[2].xyzx
                mov o2.xy, v2.xyxx
                ret 
                // Approximately 22 instruction slots used
                            
            };
            GeometryShader = NULL;
            PixelShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 10.1
                //
                //
                // Buffer Definitions: 
                //
                // cbuffer cbConstant
                // {
                //
                //   float3 vLightDir;                  // Offset:    0 Size:    12
                //      = 0xbf13b646 0x3f13b646 0xbf13b646 
                //
                // }
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim      HLSL Bind  Count
                // ------------------------------ ---------- ------- ----------- -------------- ------
                // samLinear                         sampler      NA          NA             s0      1 
                // g_txDiffuse                       texture  float4          2d             t0      1 
                // cbConstant                        cbuffer      NA          NA            cb0      1 
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_POSITION              0   xyzw        0      POS   float       
                // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                // TEXCOORD                 1   xy          2     NONE   float   xy  
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_Target                0   xyzw        0   TARGET   float   xyzw
                //
                ps_4_0
                dcl_constantbuffer CB0[1], immediateIndexed
                dcl_sampler s0, mode_default
                dcl_resource_texture2d (float,float,float,float) t0
                dcl_input_ps linear v1.xyz
                dcl_input_ps linear v2.xy
                dcl_output o0.xyzw
                dcl_temps 2
                dp3_sat r0.x, v1.xyzx, cb0[0].xyzx
                sample r1.xyzw, v2.xyxx, t0.xyzw, s0
                mul o0.xyz, r0.xxxx, r1.xyzx
                mov o0.w, l(1.000000)
                ret 
                // Approximately 5 instruction slots used
                            
            };
            DS_StencilRef = uint(0);
            DepthStencilState = EnableDepth;
            AB_BlendFactor = float4(0, 0, 0, 0);
            AB_SampleMask = uint(0xffffffff);
            BlendState = NoBlending;
        }

    }

}

