//
// FX Version: fx_4_0
// Child effect (requires effect pool): true
//
// 1 local buffer(s)
//
cbuffer $Globals
{
    float4  g_MaterialDiffuseColor;     // Offset:    0, size:   16
    float4x4 g_mWorld;                  // Offset:   16, size:   64
}

//
// 1 shared buffer(s)
//
cbuffer cbShared
{
    float3  g_LightDir;                 // Offset:    0, size:   12
    float4  g_LightDiffuse;             // Offset:   16, size:   16
    float4x4 g_mViewProj;               // Offset:   32, size:   64
    float   g_TexMove;                  // Offset:   96, size:    4
}

//
// 2 shared object(s)
//
Texture2D g_txDiffuse;
SamplerState MeshTextureSampler;

//
// 1 technique(s)
//
technique10 RenderScene10
{
    pass P0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer $Globals
            // {
            //
            //   float4 g_MaterialDiffuseColor;     // Offset:    0 Size:    16
            //   float4x4 g_mWorld;                 // Offset:   16 Size:    64
            //
            // }
            //
            // cbuffer cbShared
            // {
            //
            //   float3 g_LightDir;                 // Offset:    0 Size:    12 [unused]
            //   float4 g_LightDiffuse;             // Offset:   16 Size:    16 [unused]
            //   float4x4 g_mViewProj;              // Offset:   32 Size:    64
            //   float g_TexMove;                   // Offset:   96 Size:     4
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // $Globals                          cbuffer      NA          NA            cb0      1 
            // cbShared                          cbuffer      NA          NA            cb1      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyz         0     NONE   float   xyz 
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 0   xy          2     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
            //
            vs_4_0
            dcl_constantbuffer CB0[5], immediateIndexed
            dcl_constantbuffer CB1[7], immediateIndexed
            dcl_input v0.xyz
            dcl_input v1.xyz
            dcl_input v2.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xyz
            dcl_output o2.xy
            dcl_output o3.xyzw
            dcl_temps 2
            mov r0.xyz, v0.xyzx
            mov r0.w, l(1.000000)
            dp4 r1.x, r0.xyzw, cb0[1].xyzw
            dp4 r1.y, r0.xyzw, cb0[2].xyzw
            dp4 r1.z, r0.xyzw, cb0[3].xyzw
            dp4 r1.w, r0.xyzw, cb0[4].xyzw
            dp4 o0.x, r1.xyzw, cb1[2].xyzw
            dp4 o0.y, r1.xyzw, cb1[3].xyzw
            dp4 o0.z, r1.xyzw, cb1[4].xyzw
            dp4 o0.w, r1.xyzw, cb1[5].xyzw
            dp3 o1.x, v1.xyzx, cb0[1].xyzx
            dp3 o1.y, v1.xyzx, cb0[2].xyzx
            dp3 o1.z, v1.xyzx, cb0[3].xyzx
            add o2.y, v2.y, cb1[6].x
            mov o2.x, v2.x
            mov o3.xyzw, cb0[0].xyzw
            ret 
            // Approximately 17 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer cbShared
            // {
            //
            //   float3 g_LightDir;                 // Offset:    0 Size:    12
            //   float4 g_LightDiffuse;             // Offset:   16 Size:    16
            //   float4x4 g_mViewProj;              // Offset:   32 Size:    64 [unused]
            //   float g_TexMove;                   // Offset:   96 Size:     4 [unused]
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // MeshTextureSampler                sampler      NA          NA             s0      1 
            // MeshTextureSampler                texture  float4          2d             t0      1 
            // cbShared                          cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // TEXCOORD                 0   xyz         1     NONE   float   xyz 
            // TEXCOORD                 1   xy          2     NONE   float   xy  
            // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer CB0[2], immediateIndexed
            dcl_sampler s0, mode_default
            dcl_resource_texture2d (float,float,float,float) t0
            dcl_input_ps linear v1.xyz
            dcl_input_ps linear v2.xy
            dcl_input_ps linear v3.xyzw
            dcl_output o0.xyzw
            dcl_temps 2
            dp3_sat r0.x, v1.xyzx, cb0[0].xyzx
            mul r0.xyzw, r0.xxxx, cb0[1].xyzw
            mul r0.xyzw, r0.xyzw, v3.xyzw
            sample r1.xyzw, v2.xyxx, t0.xyzw, s0
            mul o0.xyzw, r0.xyzw, r1.xyzw
            ret 
            // Approximately 6 instruction slots used
                    
        };
    }

}

