//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   bool g_bAddSpecular;
//   float g_fHeightMapScale;
//   float g_fSpecularExponent;
//   float4 g_materialAmbientColor;
//   float4 g_materialDiffuseColor;
//   float4 g_materialSpecularColor;
//   sampler2D tBase;
//   sampler2D tNormalHeightMap;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   g_materialAmbientColor  c0       1
//   g_materialDiffuseColor  c1       1
//   g_materialSpecularColor c2       1
//   g_fSpecularExponent     c3       1
//   g_bAddSpecular          c4       1
//   g_fHeightMapScale       c5       1
//   tBase                   s0       1
//   tNormalHeightMap        s1       1
//

    ps_2_0
    def c6, 0.00999999978, 2, -1, 0
    def c7, 1, -1, 1, 0
    dcl t0.xy
    dcl t1.xyz
    dcl t2.xyz
    dcl_2d s0
    dcl_2d s1
    texld r0, t0, s1
    mov r1.xw, c6
    mad r0.x, r0.w, c5.x, r1.x
    nrm r1.xyz, t2
    rcp r0.y, r1.z
    mul r0.x, r0.y, r0.x
    mad r0.xy, r1, r0.x, t0
    texld r2, r0, s1
    texld r0, r0, s0
    mad r2, r2, c6.y, c6.z
    dp4 r2.w, r2, r2
    rsq r2.w, r2.w
    mul r2.xyz, r2.w, r2
    dp3 r2.w, r1, r2
    add r2.w, r2.w, r2.w
    mad r1.xyz, r2.w, r2, -r1
    nrm r3.xyz, r1
    nrm r1.xyz, t1
    mul r1.xyz, r1, c7
    dp3_sat r2.w, r3, r1
    dp3_sat r1.x, r2, r1
    mov r3, c1
    mad r3, r1.x, r3, c0
    pow_sat r1.x, r2.w, c3.x
    mul r2, r1.x, c2
    cmp r1, -c4.x, r1.w, r2
    mad r0, r3, r0, r1
    mov oC0, r0

// approximately 36 instruction slots used (3 texture, 33 arithmetic)
