//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4x4 g_mWorld;
//   float4x4 g_mWorldViewProj;
//   float3 g_vEyePt;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   g_mWorldViewProj c0       4
//   g_mWorld         c4       3
//   g_vEyePt         c7       1
//

    vs_2_0
    def c8, 1, 0, 0, 0
    dcl_position v0
    dcl_normal v1
    mad r0, v0.xyzx, c8.xxxy, c8.yyyx
    dp4 oPos.x, r0, c0
    dp4 oPos.y, r0, c1
    dp4 oPos.z, r0, c2
    dp4 oPos.w, r0, c3
    dp3 oT0.x, v1, c4
    dp3 oT0.y, v1, c5
    dp3 oT0.z, v1, c6
    dp4 r1.x, r0, c4
    dp4 r1.y, r0, c5
    dp4 r1.z, r0, c6
    add oT1.xyz, r1, -c7

// approximately 12 instruction slots used
