//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   sampler2D RenderTargetSampler;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   RenderTargetSampler s0       1
//

    ps_2_0
    def c0, 0.200000003, 1, 0, 0
    dcl t1.xy
    dcl t2.xy
    dcl t3.xy
    dcl t4.xy
    dcl t5.xy
    dcl t0.xy
    dcl_2d s0
    texld r0, t1, s0
    texld r1, t0, s0
    texld r2, t2, s0
    texld r3, t3, s0
    texld r4, t4, s0
    texld r5, t5, s0
    mul_sat r0.w, r0.w, r1.w
    lrp r6.xyz, r0.w, r0, r1
    mul_sat r2.w, r1.w, r2.w
    lrp r0.xyz, r2.w, r2, r1
    add r0.xyz, r0, r6
    mul_sat r0.w, r1.w, r3.w
    lrp r2.xyz, r0.w, r3, r1
    add r0.xyz, r0, r2
    mul_sat r0.w, r1.w, r4.w
    lrp r2.xyz, r0.w, r4, r1
    add r0.xyz, r0, r2
    mul_sat r0.w, r1.w, r5.w
    lrp r2.xyz, r0.w, r5, r1
    add r0.xyz, r0, r2
    mul r0.xyz, r0, c0.x
    mov r0.w, c0.y
    mov oC0, r0

// approximately 23 instruction slots used (6 texture, 17 arithmetic)
