//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   sampler2D g_samScene;
//   float4 g_vLightIntensity;
//   float4 g_vLightPosView[4];
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   g_vLightPosView   c0       4
//   g_vLightIntensity c4       1
//   g_samScene        s0       1
//

    ps_2_0
    dcl t0.xy
    dcl t1.xyz
    dcl t2.xyz
    dcl_2d s0
    texld r0, t0, s0
    add r1.xyz, -t1, c1
    dp3 r1.w, r1, r1
    rsq r2.w, r1.w
    rcp_sat r1.w, r1.w
    mul r1.xyz, r1, r2.w
    nrm r2.xyz, t2
    dp3_sat r2.w, r1, r2
    mul r2.w, r1.w, r2.w
    add r1.xyz, -t1, c0
    dp3 r1.w, r1, r1
    rsq r3.w, r1.w
    rcp_sat r1.w, r1.w
    mul r1.xyz, r1, r3.w
    dp3_sat r1.x, r1, r2
    mad r2.w, r1.x, r1.w, r2.w
    add r1.xyz, -t1, c2
    dp3 r1.w, r1, r1
    rsq r3.x, r1.w
    rcp_sat r1.w, r1.w
    mul r1.xyz, r1, r3.x
    dp3_sat r1.x, r1, r2
    mad r2.w, r1.x, r1.w, r2.w
    add r1.xyz, -t1, c3
    dp3 r1.w, r1, r1
    rsq r3.x, r1.w
    rcp_sat r1.w, r1.w
    mul r1.xyz, r1, r3.x
    dp3_sat r1.x, r1, r2
    mad r1.x, r1.x, r1.w, r2.w
    mul r0, r0, r1.x
    mul r0, r0, c4
    mov oC0, r0

// approximately 35 instruction slots used (1 texture, 34 arithmetic)
