//
// FX Version: fx_4_0
// Child effect (requires effect pool): false
//
// 2 local buffer(s)
//
cbuffer cb0
{
    float4  g_vColor = { 1, 1, 0.800000012, 1 };// Offset:    0, size:   16
    float3  g_vLightDir = { -0.707000017, 0.707000017, 0 };// Offset:   16, size:   12
    float2  g_vScreenRez = { 800, 600 };// Offset:   32, size:    8
    float   g_colorRange = 0.25;        // Offset:   40, size:    4
}

cbuffer cb1
{
    float4x4 g_mWorld;                  // Offset:    0, size:   64
    float4x4 g_mWorldViewProjection;    // Offset:   64, size:   64
}

//
// 3 local object(s)
//
BlendState NoBlending
{
    AlphaToCoverageEnable = bool(FALSE /* 0 */);
    BlendEnable[0] = bool(FALSE /* 0 */);
};
SamplerState PointSampler
{
    Filter   = uint(MIN_MAG_MIP_POINT /* 0 */);
    AddressU = uint(CLAMP /* 3 */);
    AddressV = uint(CLAMP /* 3 */);
};
SamplerState LinearSampler
{
    Filter   = uint(MIN_MAG_MIP_LINEAR /* 21 */);
    AddressU = uint(CLAMP /* 3 */);
    AddressV = uint(CLAMP /* 3 */);
};

//
// 2 technique(s)
//
technique10 Render
{
    pass P0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer cb1
            // {
            //
            //   float4x4 g_mWorld;                 // Offset:    0 Size:    64
            //   float4x4 g_mWorldViewProjection;   // Offset:   64 Size:    64
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // cb1                               cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyz         0     NONE   float   xyz 
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float   xyzw
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            //
            vs_4_0
            dcl_constantbuffer CB0[8], immediateIndexed
            dcl_input v0.xyz
            dcl_input v1.xyz
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xyz
            dcl_temps 1
            mov r0.xyz, v0.xyzx
            mov r0.w, l(1.000000)
            dp4 o0.x, r0.xyzw, cb0[4].xyzw
            dp4 o0.y, r0.xyzw, cb0[5].xyzw
            dp4 o0.z, r0.xyzw, cb0[6].xyzw
            dp4 o0.w, r0.xyzw, cb0[7].xyzw
            dp3 o1.x, v1.xyzx, cb0[0].xyzx
            dp3 o1.y, v1.xyzx, cb0[1].xyzx
            dp3 o1.z, v1.xyzx, cb0[2].xyzx
            ret 
            // Approximately 10 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer cb0
            // {
            //
            //   float4 g_vColor;                   // Offset:    0 Size:    16
            //      = 0x3f800000 0x3f800000 0x3f4ccccd 0x3f800000 
            //   float3 g_vLightDir;                // Offset:   16 Size:    12
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float2 g_vScreenRez;               // Offset:   32 Size:     8 [unused]
            //      = 0x44480000 0x44160000 
            //   float g_colorRange;                // Offset:   40 Size:     4 [unused]
            //      = 0x3e800000 
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // cb0                               cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Position              0   xyzw        0      POS   float       
            // NORMAL                   0   xyz         1     NONE   float   xyz 
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_Target                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer CB0[2], immediateIndexed
            dcl_input_ps linear v1.xyz
            dcl_output o0.xyzw
            dcl_temps 1
            dp3 r0.x, v1.xyzx, v1.xyzx
            rsq r0.x, r0.x
            mul r0.xyz, r0.xxxx, v1.xyzx
            dp3_sat r0.x, r0.xyzx, cb0[1].xyzx
            mul o0.xyzw, r0.xxxx, cb0[0].xyzw
            ret 
            // Approximately 6 instruction slots used
                    
        };
        AB_BlendFactor = float4(0, 0, 0, 0);
        AB_SampleMask = uint(0xffffffff);
        BlendState = NoBlending;
    }

}

technique10 RenderQuad
{
    pass P0
    {
        VertexShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // POSITION                 0   xyzw        0     NONE   float   xyzw
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_POSITION              0   xyzw        0      POS   float   xyzw
            // TEXCOORD                 0   xy          1     NONE   float   xy  
            //
            vs_4_0
            dcl_input v0.xyzw
            dcl_input v1.xy
            dcl_output_siv o0.xyzw, position
            dcl_output o1.xy
            mov o0.xyzw, v0.xyzw
            mov o1.xy, v1.xyxx
            ret 
            // Approximately 3 instruction slots used
                    
        };
        GeometryShader = NULL;
        PixelShader = asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 10.1
            //
            //
            // Buffer Definitions: 
            //
            // cbuffer cb0
            // {
            //
            //   float4 g_vColor;                   // Offset:    0 Size:    16 [unused]
            //      = 0x3f800000 0x3f800000 0x3f4ccccd 0x3f800000 
            //   float3 g_vLightDir;                // Offset:   16 Size:    12 [unused]
            //      = 0xbf34fdf4 0x3f34fdf4 0x00000000 
            //   float2 g_vScreenRez;               // Offset:   32 Size:     8
            //      = 0x44480000 0x44160000 
            //   float g_colorRange;                // Offset:   40 Size:     4
            //      = 0x3e800000 
            //
            // }
            //
            //
            // Resource Bindings:
            //
            // Name                                 Type  Format         Dim      HLSL Bind  Count
            // ------------------------------ ---------- ------- ----------- -------------- ------
            // cb0                               cbuffer      NA          NA            cb0      1 
            //
            //
            //
            // Input signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_POSITION              0   xyzw        0      POS   float   x   
            // TEXCOORD                 0   xy          1     NONE   float       
            //
            //
            // Output signature:
            //
            // Name                 Index   Mask Register SysValue  Format   Used
            // -------------------- ----- ------ -------- -------- ------- ------
            // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
            //
            ps_4_0
            dcl_constantbuffer CB0[3], immediateIndexed
            dcl_input_ps_siv linear noperspective v0.x, position
            dcl_output o0.xyzw
            dcl_temps 1
            add r0.x, v0.x, l(-0.500000)
            div r0.x, r0.x, cb0[2].x
            mul o0.xyz, r0.xxxx, cb0[2].zzzz
            mov o0.w, l(1.000000)
            ret 
            // Approximately 5 instruction slots used
                    
        };
        AB_BlendFactor = float4(0, 0, 0, 0);
        AB_SampleMask = uint(0xffffffff);
        BlendState = NoBlending;
    }

}

