//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   samplerCUBE envmap_sampler;
//   sampler2D linear_sampler;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   linear_sampler s0       1
//   envmap_sampler s1       1
//

    ps_2_0
    def c0, 1, 0, 0, 0
    dcl v0.xyz
    dcl v1.xyz
    dcl t0.xy
    dcl t1.xyz
    dcl t2.x
    dcl_2d s0
    dcl_cube s1
    texld r0, t1, s1
    texld r1, t0, s0
    mul r0.xyz, r0, t2.x
    mad r0.xyz, v0, r1, r0
    add r0.xyz, r0, v1
    mov r0.w, c0.x
    mov oC0, r0

// approximately 7 instruction slots used (2 texture, 5 arithmetic)
