//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// t0                                texture  float4        2dMS             t0      1 
// t1                                texture  float4       2dMS8             t1      1 
// t2                                texture  float4  2darrayMS8             t2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE     int   xy  
// TEXCOORD                 1   xyzw        1     NONE     int    y  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_texture2dms(0) (float,float,float,float) t0
dcl_resource_texture2dms(8) (float,float,float,float) t1
dcl_resource_texture2dmsarray(8) (float,float,float,float) t2
dcl_input_ps constant v0.xy
dcl_input_ps constant v1.y
dcl_output o0.xyzw
dcl_temps 1
samplepos r0.xy, t0.xyxx, v0.x
samplepos r0.zw, rasterizer.xxxy, l(0)
add r0.xy, r0.zwzz, r0.xyxx
samplepos r0.zw, rasterizer.xxxy, l(1)
add r0.xy, r0.zwzz, r0.xyxx
samplepos r0.zw, rasterizer.xxxy, v0.y
add r0.xy, r0.zwzz, r0.xyxx
samplepos r0.zw, rasterizer.xxxy, v1.y
add o0.xy, r0.zwzz, r0.xyxx
samplepos r0.xy, t0.xyxx, v1.y
samplepos r0.zw, t1.xxxy, l(0)
add r0.xy, r0.zwzz, r0.xyxx
samplepos r0.zw, t1.xxxy, l(1)
add r0.xy, r0.zwzz, r0.xyxx
samplepos r0.zw, t2.xxxy, l(0)
add r0.xy, r0.zwzz, r0.xyxx
iadd r0.z, v0.y, l(2)
samplepos r0.zw, t2.xxxy, r0.z
add r0.xy, r0.zwzz, r0.xyxx
sampleinfo r0.z, rasterizer.x
add o0.z, r0.z, r0.x
mov o0.w, r0.y
ret 
// Approximately 23 instruction slots used
