//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// buf                                   UAV    byte         r/w             u0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_raw u0
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 4, 2, 1
iadd r0.x, vThreadGroupID.x, vThreadID.x
iadd r0.x, r0.x, vThreadIDInGroupFlattened.x
iadd r0.x, r0.x, vThreadIDInGroup.x
atomic_cmp_store u0, l(0), l(1), r0.x
ret 
// Approximately 5 instruction slots used
