//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   sampler2D s0;
//   float4 tcLumOffsets[4];
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   tcLumOffsets c0       4
//   s0           s0       1
//

    ps_3_0
    def c4, -1.00000002e+020, 9.99999975e-006, 0.173286796, 1.44269502
    def c5, 0, 1, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    add r0.xy, c0, v0
    texld r0, r0, s0
    max r1.x, r0.y, r0.z
    max r2.x, r0.x, r1.x
    max r0.x, c4.x, r2.x
    add r0.y, r2.x, c4.y
    log r0.y, r0.y
    add r0.zw, c1.xyxy, v0.xyxy
    texld r1, r0.zwzw, s0
    max r0.z, r1.y, r1.z
    max r2.x, r1.x, r0.z
    max r1.x, r0.x, r2.x
    add r0.x, r2.x, c4.y
    log r0.x, r0.x
    mul r0.x, r0.x, c4.z
    mad r0.x, r0.y, c4.z, r0.x
    add r0.yz, c2.xxyw, v0.xxyw
    texld r2, r0.yzzw, s0
    max r0.y, r2.y, r2.z
    max r1.y, r2.x, r0.y
    max r0.y, r1.x, r1.y
    add r0.z, r1.y, c4.y
    log r0.z, r0.z
    mad r0.x, r0.z, c4.z, r0.x
    add r0.zw, c3.xyxy, v0.xyxy
    texld r1, r0.zwzw, s0
    max r0.z, r1.y, r1.z
    max r2.x, r1.x, r0.z
    max oC0.y, r0.y, r2.x
    add r0.y, r2.x, c4.y
    log r0.y, r0.y
    mad r0.x, r0.y, c4.z, r0.x
    mul r0.x, r0.x, c4.w
    exp oC0.x, r0.x
    mov oC0.zw, c5.xyxy

// approximately 35 instruction slots used (4 texture, 31 arithmetic)
